
AutoGrad

In [ ]:
import torch
import numpy as np

In [ ]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

In [3]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [4]:
# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

False False
None
True
None
True
True
False


In [5]:
#Let's walk in through one last example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
