In [ ]:
import torch
import torch.nn as nn

In [ ]:
layer = nn.Linear(5,5)

In [ ]:
layer.weight.data
# .data gives only the tensor of the values and removes any additonal info

Uniform Distribution

In [ ]:
nn.init.uniform_(layer.weight.data, a=0.0, b=1.0)
# '_' means in-place operation

Normal Distribution

In [ ]:
nn.init.normal_(layer.weight.data, mean=0.0, std=1.0)

Constant

In [16]:
nn.init.constant_(layer.bias, 2)

Parameter containing:
tensor([2., 2., 2., 2., 2.], requires_grad=True)

Zeros

In [17]:
nn.init.zeros_(layer.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

Xavier Uniform Distribution

In [18]:
nn.init.xavier_uniform_(layer.weight.data, gain=1.0)

tensor([[ 0.5474, -0.6984,  0.3253,  0.1176, -0.0244],
        [ 0.5604,  0.4440, -0.4842, -0.6803, -0.1743],
        [-0.1829,  0.5902,  0.3731, -0.0398,  0.4053],
        [-0.6085, -0.4831, -0.4508,  0.0455, -0.2551],
        [ 0.2136, -0.6822, -0.4294,  0.0169, -0.7304]])

Xavier Normal Distribution

In [19]:
nn.init.xavier_normal_(layer.weight.data, gain=1.0)

tensor([[ 0.4323,  0.2011, -0.2129, -0.2683,  0.5422],
        [ 0.3702,  1.2291, -0.1552, -0.1071,  0.2163],
        [-0.0900,  0.5819,  0.0077,  0.7780, -0.0432],
        [ 0.2023,  0.2519, -0.3070, -0.6508,  0.4915],
        [-0.4007, -0.1754,  0.4997, -0.0310,  0.2851]])